"""add core business entities

Revision ID: 772f1e83d5df
Revises: 0001_initial
Create Date: 2026-07-11 15:25:11.093847
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "772f1e83d5df"
down_revision: str | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category")),
    )
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_category_name"), ["name"], unique=True)

    op.create_table(
        "competitor",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competitor")),
    )
    with op.batch_alter_table("competitor", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_competitor_name"), ["name"], unique=True)

    op.create_table(
        "product",
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("unit_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("base_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("base_price >= 0", name=op.f("ck_product_base_price_non_negative")),
        sa.CheckConstraint("unit_cost >= 0", name=op.f("ck_product_unit_cost_non_negative")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
            name=op.f("fk_product_category_id_category"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product")),
    )
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_product_category_id"), ["category_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_product_sku"), ["sku"], unique=True)

    op.create_table(
        "competitor_price",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("competitor_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("observed_at", sa.Date(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("price >= 0", name=op.f("ck_competitor_price_price_non_negative")),
        sa.ForeignKeyConstraint(
            ["competitor_id"],
            ["competitor.id"],
            name=op.f("fk_competitor_price_competitor_id_competitor"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_competitor_price_product_id_product"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competitor_price")),
        sa.UniqueConstraint(
            "product_id",
            "competitor_id",
            "observed_at",
            name="uq_competitor_price_product_competitor_observed",
        ),
    )
    with op.batch_alter_table("competitor_price", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_competitor_price_competitor_id"), ["competitor_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_competitor_price_product_id"), ["product_id"], unique=False
        )

    op.create_table(
        "historical_sale",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("sale_date", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity >= 0", name=op.f("ck_historical_sale_quantity_non_negative")),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_historical_sale_unit_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_historical_sale_product_id_product"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_historical_sale")),
    )
    with op.batch_alter_table("historical_sale", schema=None) as batch_op:
        batch_op.create_index(
            "ix_historical_sale_product_date", ["product_id", "sale_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_historical_sale_sale_date"), ["sale_date"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("historical_sale", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_historical_sale_sale_date"))
        batch_op.drop_index("ix_historical_sale_product_date")

    op.drop_table("historical_sale")
    with op.batch_alter_table("competitor_price", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_competitor_price_product_id"))
        batch_op.drop_index(batch_op.f("ix_competitor_price_competitor_id"))

    op.drop_table("competitor_price")
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_sku"))
        batch_op.drop_index(batch_op.f("ix_product_category_id"))

    op.drop_table("product")
    with op.batch_alter_table("competitor", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_competitor_name"))

    op.drop_table("competitor")
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_category_name"))

    op.drop_table("category")
    # ### end Alembic commands ###
